### ISSUE TITLE
有关有人盗用了您的代码但未遵循GPL v3协议一事

### ISSUE THREAD

**Issue by wuwenyuan819** [zhiyiYo/Groove#100]
您好，我们最近在对高雅不堪的逆天人士进行批评教育时发现其使用了您的源代码但并未遵循GPL v3进行开源。

详情可在 https://syl.skin/ 的“SYL 音乐”一栏进行查阅。

他们声称使用了Groove作为开源项目，且该并高级知识分子未习得由学校所教授的python3除外的语言。此外，我们未在网上搜寻到他们公开的修改过后的源代码。所以我们有理由怀疑他使用了您的代码但并未遵循GPL v3协议。

如果您有雅兴，可以[下载](https://ms.syl.skin/Apps_SYL)他们神必无比的SYL音乐APP进行酣畅淋漓的体验以知晓这件史诗的曼妙之处。

如果您在短时间内查阅了该issue，那么他们的网站可能已经被正义人士制裁，导致无法访问。

该issue仅仅作为一个通知，如果打扰或者冒犯了您，我对此感到抱歉，并且您可以随意关闭该issue。

**Comment by zhiyiYo** [comment]
感谢阁下的提醒，目前该网站已处于停用状态
