### ISSUE TITLE
大佬的ui是怎么设计的？

### ISSUE THREAD

**Issue by hunye** [zhiyiYo/Groove#14]
小白最近在学习pyqt，书上教的是用qt designer设计好，然后把.ui文件转成.py文件。不知道大佬怎么设计的这么好看的？
顺便问一下这么大的项目建议从哪里入手看鸭？

**Comment by zhiyiYo** [comment]
关于界面设计的话我是对照着 Groove 音乐的界面设计的，然后这个项目的话其实可以从view文件夹里面的那些界面文件看起，其中 main_window 是主界面，里面有很多信号和槽的连接。
