### ISSUE TITLE
亚克力板拖动

### ISSUE THREAD

**Issue by xiaoye-hhh** [zhiyiYo/Groove#15]
也许可以在拖动时暂时关闭亚克力板的效果来提升流畅性。

拖动时导航栏正好是处于收缩的状态，是否开启亚克力板效果区别不大，但是能大幅提高流畅性。

**Comment by zhiyiYo** [comment]
如果导航栏展开了呢，感觉会有所区别

**Comment by xiaoye-hhh** [comment]
- - 好像点击titlebar拖动的时候，那个导航栏会自动收索，就是说不会存在展开拖动的情况

**Comment by zhiyiYo** [comment]
是这样的，导航栏有三种状态：收缩、展开、弹出菜单，在窗口宽度较小的时候是弹出菜单，这时候会自己收缩回去，宽度较大的时候就是正常的展开状态了，不会自动收缩的

**Comment by xiaoye-hhh** [comment]
哦- -，没发现，那确实不是很合适。

**Comment by zhiyiYo** [comment]
终极解决方案就是升级到win11
