### ISSUE TITLE
测试文件运行

### ISSUE THREAD

**Issue by xiaoye-hhh** [zhiyiYo/Groove#16]
我将项目克隆后用pycharm打开，运行test下的测试文件，报错找不到模块，我只知道可以将导包写成绝对导入解决，但是特别麻烦，有什么解决办法嘛？

**Comment by zhiyiYo** [comment]
测试文件我是放在根目录下运行没问题后又放在tests文件夹的，其实这些文件意义不大。实际上应该用unittest来写，这样可以直接点击左侧的运行按钮（VS Code 下是没有问题的，没用过pycharm）
