### ISSUE TITLE
高分屏下软件看起来很小

### ISSUE THREAD

**Issue by luosaidage** [zhiyiYo/Groove#19]
如图：
![image](https://user-images.githubusercontent.com/23243630/156954058-50f339ef-2548-4c96-b557-a0fcfac5485e.png)

软件做得跟系统带的grove简直一模一样（外观），但是还有一些地方可以改进。
1、歌手那个按钮的功能好像还没实现。
2、我点击歌曲、歌手、专辑时字体会放大，这跟系统自带的有点不一样，而且由于我的高分屏，点击之后字大得有一部分看不到了。
3、系统自带得grove的左边条是半透明的。
4、高分屏下软件看起来很小。

**Comment by zhiyiYo** [comment]
感谢关注，歌手标签界面暂时还没实现，因为感觉专辑标签界面可以按照歌手排序，所以歌手标签界面我就没写了。

高分屏的话主要是缩放之后标题栏的图标会糊掉，然后我写这个软件的时候是按1.25缩放来写的，在1920*1080上看起来还蛮大的，如果在代码里面再把缩放开起来这个软件看起来就更大了，所以就没弄了。如果要开缩放的话，这个软件的字体大小差不多要重写一遍，感觉工作量有点大。

导航栏亚克力半透明可以在设置界面开起来，但是可能会造成界面拖拽卡顿问题，所以默认我把它关了。

以上～

**Comment by zhiyiYo** [comment]
我现在启用了 DPI 缩放，代码可以从 beta 分支拉取，如果测试没问题的话，打算合并到 master😊

**Comment by zhiyiYo** [comment]
由于该 issue 不在活跃，所以暂时关闭

**Comment by zhiyiYo** [comment]
目前已完成歌手标签页
