### ISSUE TITLE
使用中的一些小问题 :)

### ISSUE THREAD

**Issue by jackieshen357** [zhiyiYo/Groove#21]
Salve! 首先衷心赞叹，您的程序制作能力让我折服，您的设计与代码已经达到了艺术品的标准！
但在学习的过程中，我发现了一些瑕不掩瑜的小问题：
1. 我在我的Win10和Win11系统上的测试中，均出现了播放列表一点击就闪退的情况，同时弹出以下报错：
![image](https://user-images.githubusercontent.com/88727061/166140526-48ae0a1b-8a08-495a-926c-14046d16c140.png)
2. 当在播放页面通过三个点的窗口添加歌曲到个人播放列表时，会默认将当前播放列表内的所有歌曲全部添加（默认为17首歌被全部添加）；
3. 在Win10系统上使用时，程序刚启动的阶段，会出现软件卡在屏幕上部的情况且无法移动，此时需手动点击边框才能恢复；
4. 如图，搜索结果的显示中会出现文字被遮盖的现象，不能完全显示（Win10）：
![image](https://user-images.githubusercontent.com/88727061/166140850-22966ad0-5e1f-46e0-ab61-a9223cc099a1.png)

以及一些个人的小建议：
1. 导航栏中的最小化按钮可否设计为“鼠标移入触发，且当鼠标移除导航栏时自动收回“与”鼠标点击时导航栏常驻，但再次点击其他窗口部件时自动回收“？
2. 在歌曲的播放页面中通过三个点添加歌曲至自定义歌单，默认均为新建一个歌单，可否添加歌曲至已存在的歌单？

以上，感谢 ~

**Comment by zhiyiYo** [comment]
在我发布的 exe 上会出现这些 bug 吗，我看你的截图里面也没有使用虚拟环境

**Comment by zhiyiYo** [comment]
我测试了一下，把在线歌曲添加到自定义播放列表确实会出现问题 1 中的 bug，今晚修复一下，感谢反馈！

**Comment by zhiyiYo** [comment]
如果你想要添加某几首歌曲到某一个自定义播放列表的话，可以参照我动图里面的方式，选中歌曲卡的复选框，然后在底部的选择模式栏中点击添加到，选择你要添加的那个播放列表就好了

**Comment by zhiyiYo** [comment]
目前已修复问题 1

**Comment by jackieshen357** [comment]
> 

exe我没有测试过，我用的是代码
测试的时候是否开启虚拟环境的结果是一样的 :)

**Comment by zhiyiYo** [comment]
最好还是在虚拟环境里面测试，以免出现各种奇怪的闪退问题

**Comment by jackieshen357** [comment]
> 如果你想要添加某几首歌曲到某一个自定义播放列表的话，可以参照我动图里面的方式，选中歌曲卡的复选框，然后在底部的选择模式栏中点击添加到，选择你要添加的那个播放列表就好了

我是指在不进入 当前播放列表 的情况下，直接仅添加当前播放的歌曲

**Comment by zhiyiYo** [comment]
不进入 PlayingInterface 如何对正在播放的歌曲进行操作？🤔

**Comment by jackieshen357** [comment]
> 不进入 PlayingInterface 如何对正在播放列表的歌曲进行操作？🤔

![image](https://user-images.githubusercontent.com/88727061/166145843-947fc0cb-bbc3-4b4d-b912-34c36fad4a9c.png)
就是在这个位置是否可以有 保存到播放列表，而不只是 保存为播放列表？

**Comment by zhiyiYo** [comment]
哦哦，明白你的意思了，确实可以考虑再加一个添加到子菜单😇

**Comment by jackieshen357** [comment]
以及补充一个新发现：如果在控制台终止程序（不手动在系统托盘中右键退出），则Groove的图标将会一直在托盘中堆积，直到鼠标移上去才会消失，如图：
![image](https://user-images.githubusercontent.com/88727061/166146041-301f46c7-bd76-4cb2-9977-a5b0f900f674.png)

**Comment by zhiyiYo** [comment]
> 以及补充一个新发现：如果在控制台终止程序（不手动在系统托盘中右键退出），则Groove的图标将会一直在托盘中堆积，直到鼠标移上去才会消失，如图： ![image](https://user-images.githubusercontent.com/88727061/166146041-301f46c7-bd76-4cb2-9977-a5b0f900f674.png)

这个问题我一直解决不了，脑壳疼

**Comment by jackieshen357** [comment]
更新版的（即修复了问题1的）版本出现新的问题：虽然现在点击播放列表不会闪退，但点开后歌曲没有显示出来。（虚拟环境测试）

**Comment by zhiyiYo** [comment]
> 更新版的（即修复了问题1的）版本出现新的问题：虽然现在点击播放列表不会闪退，但点开后歌曲没有显示出来。（虚拟环境测试）

这不是 bug，而是 feature 😅
因为我过滤了在线歌曲，这些在线歌曲的歌曲信息不会保存到数据库中，所以不可能从歌曲信息表里面把他们读出来

**Comment by jackieshen357** [comment]
> > 更新版的（即修复了问题1的）版本出现新的问题：虽然现在点击播放列表不会闪退，但点开后歌曲没有显示出来。（虚拟环境测试）
> 
> 这不是 bug，而是 feature 😅 因为我过滤了在线歌曲，这些在线歌曲的歌曲信息不会保存到数据库中，所以不可能从歌曲信息表里面把他们读出来

可否通过”曲线救国“的方式加强交互性，比如在线歌曲添加=后台自动下载+添加 :D

**Comment by zhiyiYo** [comment]
也许可以考虑加一个在线音乐信息表，但是这对酷我有一定的依赖，万一日后酷我的接口挂了就难搞了😕

**Comment by zhiyiYo** [comment]
> 以及补充一个新发现：如果在控制台终止程序（不手动在系统托盘中右键退出），则Groove的图标将会一直在托盘中堆积，直到鼠标移上去才会消失，如图： ![image](https://user-images.githubusercontent.com/88727061/166146041-301f46c7-bd76-4cb2-9977-a5b0f900f674.png)

其实我感觉这个也不能算是问题，因为运行 exe 就只能靠右键或者关闭按钮退出，不存在终端退出的问题

**Comment by jackieshen357** [comment]
所以可以除了在线直接播放外的操作其他都交给电脑来做，比如通过 在线添加到个人播放列表 的歌也下载到本地后在添加，以减少对服务器的依赖。
在线音乐信息表可能会导致服务器访问过于频繁，因为我使用时就经常出现504报错（甚至只是挂了会机），而且播放时流畅度不会比下载后添加的高。

**Comment by zhiyiYo** [comment]
> 所以可以除了在线直接播放外的操作其他都交给电脑来做，比如通过 在线添加到个人播放列表 的歌也下载到本地后在添加，以减少对服务器的依赖。 在线音乐信息表可能会导致服务器访问过于频繁，因为我使用时就经常出现504报错（甚至只是挂了会机），而且播放时流畅度不会比下载后添加的高。

我寻思着在网抑云里面添加歌曲到个人播放列表也不至于先下载一波啊

**Comment by jackieshen357** [comment]
> > 以及补充一个新发现：如果在控制台终止程序（不手动在系统托盘中右键退出），则Groove的图标将会一直在托盘中堆积，直到鼠标移上去才会消失，如图： ![image](https://user-images.githubusercontent.com/88727061/166146041-301f46c7-bd76-4cb2-9977-a5b0f900f674.png)
> 
> 其实我感觉这个也不能算是问题，因为运行 exe 就只能靠右键或者关闭按钮退出，不存在终端退出的问题

这个确实不是问题，但我看源码学习的时候喜欢直接终端终止，所以经常会弄出十几个图标 :) 不过不去管它也没关系

**Comment by zhiyiYo** [comment]
> > > 以及补充一个新发现：如果在控制台终止程序（不手动在系统托盘中右键退出），则Groove的图标将会一直在托盘中堆积，直到鼠标移上去才会消失，如图： ![image](https://user-images.githubusercontent.com/88727061/166146041-301f46c7-bd76-4cb2-9977-a5b0f900f674.png)
> > 
> > 
> > 其实我感觉这个也不能算是问题，因为运行 exe 就只能靠右键或者关闭按钮退出，不存在终端退出的问题
> 
> 这个确实不是问题，但我看源码学习的时候喜欢直接终端终止，所以经常会弄出十几个图标 :) 不过不去管它也没关系

如果切换到直接关闭而不是最小到托盘，即使直接终端退出应该也不会出现这个问题

**Comment by zhiyiYo** [comment]
关于在线音乐歌曲卡文字被截断的问题，我的系统还是 Windows10 的时候没出现该问题，能否多提供一些环境信息，比如设置里面的 DPI 缩放比

**Comment by jackieshen357** [comment]
> > 所以可以除了在线直接播放外的操作其他都交给电脑来做，比如通过 在线添加到个人播放列表 的歌也下载到本地后在添加，以减少对服务器的依赖。 在线音乐信息表可能会导致服务器访问过于频繁，因为我使用时就经常出现504报错（甚至只是挂了会机），而且播放时流畅度不会比下载后添加的高。
> 
> 我寻思着在网抑云里面添加歌曲到个人播放列表也不至于先下载一波啊

我只是随口一说，别在意:) 程序里面的东西我还没学完，您的判断肯定比我要准确 :D

**Comment by zhiyiYo** [comment]
> > > 所以可以除了在线直接播放外的操作其他都交给电脑来做，比如通过 在线添加到个人播放列表 的歌也下载到本地后在添加，以减少对服务器的依赖。 在线音乐信息表可能会导致服务器访问过于频繁，因为我使用时就经常出现504报错（甚至只是挂了会机），而且播放时流畅度不会比下载后添加的高。
> > 
> > 
> > 我寻思着在网抑云里面添加歌曲到个人播放列表也不至于先下载一波啊
> 
> 我只是随口一说，别在意:) 程序里面的东西我还没学完，您的判断肯定比我要准确 :D
其实我觉得与其保存在线音乐信息，不如让用户自己下载去。

当程序能跑起来时，就千万不要去动它了.jpg😊

**Comment by zhiyiYo** [comment]
> 关于在线音乐歌曲卡文字被截断的问题，我的系统还是 Windows10 的时候没出现该问题，能否多提供一些环境信息，比如设置里面的 DPI 缩放比

@jackieshen357

**Comment by jackieshen357** [comment]
> > 关于在线音乐歌曲卡文字被截断的问题，我的系统还是 Windows10 的时候没出现该问题，能否多提供一些环境信息，比如设置里面的 DPI 缩放比
> 
> @jackieshen357

测试环境：1366×768，缩放100%
事实上，当我将屏幕缩放调整为125%时，不再出现截断现象（即仅当缩放为100%会出现问题）

**Comment by zhiyiYo** [comment]
🤔我测试一下

**Comment by zhiyiYo** [comment]
确实发生了截断，待会儿修复一下😇

**Comment by zhiyiYo** [comment]
@jackieshen357 
我在电脑上测试了新代码，发现 100% 缩放不会被截断，目前已将代码推送上去了，不知道你那边更新代码后情况如何？

**Comment by jackieshen357** [comment]
> @jackieshen357 我在自己电脑上测试了新代码，发现 100% 缩放不会被截断，目前已将代码推送上去了，不知道你那边更新代码后情况如何？

 :) 截断问题已经得到解决！

**Comment by jackieshen357** [comment]
但我也注意到一个细节问题：搜索界面本地歌曲和在线歌曲可以同时被选中
![image](https://user-images.githubusercontent.com/88727061/166153327-e850675d-14ea-4d4c-bd9c-a5063fac5dae.png)

**Comment by zhiyiYo** [comment]
> 但我也注意到一个细节问题：搜索界面本地歌曲和在线歌曲可以同时被选中 ![image](https://user-images.githubusercontent.com/88727061/166153327-e850675d-14ea-4d4c-bd9c-a5063fac5dae.png)

因为两个歌曲卡列表控件没有互相通信，所以可以同时选中，感觉要互斥还挺麻烦的😕

**Comment by zhiyiYo** [comment]
@jackieshen357 
关于问题 3，可以试下把 main_window.py 中 `initWindow()` 第一行的 `DBInitializer.init()` 移动到第 57 行，在显示界面之前就和数据库建立连接，这样应该不会卡住界面

**Comment by jackieshen357** [comment]
> @jackieshen357 关于问题 3，可以动图演示一下吗

 如图：刚启动的界面会卡在屏幕上方且无法移动，需手动点击边框后才可拖动
![卡界面](https://user-images.githubusercontent.com/88727061/166180197-6cc32db0-6ef6-465c-ad22-8d4849b84ea9.gif)

**Comment by zhiyiYo** [comment]
有点奇怪，我没看见标题栏，Groove 是超出你屏幕了吗

**Comment by jackieshen357** [comment]
> 有点奇怪，我没看见标题栏，Groove 是超出你屏幕了吗

是的，包括标题栏和控制按钮在内的部分全部卡在了屏幕外面

**Comment by zhiyiYo** [comment]
有点不太对劲啊，我初始化的时候 resize 的尺寸是根据屏幕的大小来缩放的，而且也会居中显示才对啊

**Comment by jackieshen357** [comment]
根据我的观察，应该是初始化窗口的摆放位置出现了问题（不能适配每一种分辨率），因为当我把`main_window.py`中第217行由
`        self.move(w//2 - self.width()//2, h//2 - self.height()//2)`
改为
`        self.move(w//2 - self.width()//2, h//2 - self.height()//2 + 130)`
时，窗口打开位置恢复正常，同时也可知出现问题3是因为窗口被初始化到屏幕外去了 :)

**Comment by zhiyiYo** [comment]
我看动图里面窗口往右上角偏移了，如果直接加上130的 y 轴偏移量，水平方向还是没有居中诶，而且强行 +130 可能导致窗口底部超出显示屏

**Comment by jackieshen357** [comment]
> 我看动图里面窗口往右上角偏移了，如果直接加上130的 y 轴偏移量，水平方向还是没有居中诶，而且强行 +130 可能导致窗口底部超出显示屏

没有没有，动图里看上去偏移了是因为最右边一块是gif的录制操纵区，没有录制下来，水平方向一直是居中的没有问题
不过我认为最好窗口能根据不同分辨率动态调整大小，不然在一些较小的分辨率（1280×600）下会出现上下同时超出屏幕

**Comment by zhiyiYo** [comment]
我又看了下代码，发现居然没有根据分辨率进行窗口大小调整，只考虑了 DPI 缩放比：
```python
self.resize(1240/r, 970/r)
self.setMinimumSize(1030/r, 800/r)
```
这两行代码修改一下应该就没问题了😇

**Comment by zhiyiYo** [comment]
@jackieshen357 
把 main_window.py 的 207-208 行改成：
```python
self.resize(w*1240/1920, h*970/1080)
self.setMinimumSize(w*1030/1920, h*800/1080)
```
还会出现窗口超出显示屏的情况吗

**Comment by jackieshen357** [comment]
窗口不会超出显示屏了 :D 
但有一个细节，动态改变的窗口中的字体最好能和窗口一起改变大小

**Comment by zhiyiYo** [comment]
> 窗口不会超出显示屏了 :D 但有一个细节，动态改变的窗口中的字体最好能和窗口一起改变大小

你是说改变 DPI 缩放比的时候改变字体大小吗？

**Comment by jackieshen357** [comment]
> > 窗口不会超出显示屏了 :D 但有一个细节，动态改变的窗口中的字体最好能和窗口一起改变大小
> 
> 你是说改变 DPI 缩放比的时候改变字体大小吗？

不同分辨率情况下初始化的窗口及全屏时的文字大小都是一样的，也就是说刚启动时出现的界面在调整后会显得字很大
![image](https://user-images.githubusercontent.com/88727061/166198943-0a726b36-5202-4f02-8be6-8e377b2d00ff.png)

**Comment by zhiyiYo** [comment]
@jackieshen357 
因为我刚开始写样式的时候用的就是 125% 缩放比的字体，现在不可能再改回 100% 的缩放比了，当显示器的 DPI 缩放比为 100%~125% 之间时字体都是这么大，如果超过了 125% 则会增大字体大小，具体代码可以参见 Groove.py 的第 13 行：
```python
os.environ["QT_SCALE_FACTOR"] = str(max(1, getDevicePixelRatio()-0.25))
```

**Comment by zhiyiYo** [comment]
> 导航栏中的最小化按钮可否设计为“鼠标移入触发，且当鼠标移除导航栏时自动收回“与”鼠标点击时导航栏常驻，但再次点击其他窗口部件时自动回收“？

如果窗口宽度较小，点击按钮弹出的会是导航菜单，这时候点击其他部件会自动回收菜单

**Comment by zhiyiYo** [comment]
由于该 issue 不再活跃，所以我暂时关闭它，如果有碰到任何问题可以再次打开

**Comment by zhiyiYo** [comment]
> 但我也注意到一个细节问题：搜索界面本地歌曲和在线歌曲可以同时被选中 ![image](https://user-images.githubusercontent.com/88727061/166153327-e850675d-14ea-4d4c-bd9c-a5063fac5dae.png)

目前已修复同时选中的问题

**Comment by zhiyiYo** [comment]
目前已支持添加任意本地或者在线歌曲到自定义播放列表中。
