### ISSUE TITLE
PIL.Image 转换为 QPixmap的bug

### ISSUE THREAD

**Issue by 1197730656** [zhiyiYo/Groove#22]
在common/image_process_utils.py文件中的  getBlurPixmap函数中
    image = gaussianBlur(imagePath, blurRadius, brightFactor, blurPicSize)  # 这里返回的是 Numpy图像 
    return Image.fromarray(image).toqpixmap()

在我的win10系统 python3.7.7 Pillow==8.4.0  PyQt5==5.15.6 的环境中  程序会崩溃  
这可能是 PIL和PyQt5的bug   PIL.Image 对象转QPixmap对象时的bug
以下的链接是 一种解决方式
https://stackoverflow.com/questions/34697559/pil-image-to-qpixmap-conversion-issue

**Comment by zhiyiYo** [comment]
如果是虚拟环境应该不会出现这种问题吧

**Comment by zhiyiYo** [comment]
@1197730656 
可以把上传一下出现问题的歌曲吗，我测试一下

**Comment by 1197730656** [comment]
[MADILYN - Closer.zip](https://github.com/zhiyiYo/Groove/files/8785716/MADILYN.-.Closer.zip)

**Comment by zhiyiYo** [comment]
我在虚拟环境中并没有出现该 bug，也许你应该试试 exe 会不会报错，不会报错的话应该就是 PIL 和 PyQt 的版本问题
![image](https://user-images.githubusercontent.com/65096819/170677492-d8ecaf07-11a4-4f71-904a-8c8ae1912887.png)

**Comment by 1197730656** [comment]
> 

嗯 我使用虚拟环境就不存在这个问题了，应该是我Pillow 和 PyQt5版本问题。
