### ISSUE TITLE
无法解析此音频，请检查LAV filters是否已正确安装

### ISSUE THREAD

**Issue by Harry2010410** [zhiyiYo/Groove#23]
win10 已安装LAV filters，但是在播放音乐时还是弹出“无法解析此音频，请检查LAV filters是否已正确安装”错误

**Comment by zhiyiYo** [comment]
播放的音频可以发一下吗，我测试一下

**Comment by zhiyiYo** [comment]
@Harry2010410

**Comment by Harry2010410** [comment]
[梁静茹 - 勇气.zip](https://github.com/zhiyiYo/Groove/files/8897802/-.zip)
我这个是用的在线搜索的音频，安装完LAV需要做什么设置吗

**Comment by zhiyiYo** [comment]
> [梁静茹 - 勇气.zip](https://github.com/zhiyiYo/Groove/files/8897802/-.zip) 我这个是用的在线搜索的音频，安装完LAV需要做什么设置吗

我这边播放很正常，如果安装成功了也不需要任何额外的设置
![image](https://user-images.githubusercontent.com/65096819/173532183-b8226790-73c0-440f-84ed-8dc654856969.png)

**Comment by zhiyiYo** [comment]
安装成功之后应该能在搜索里面找到 LAV Audio
![image](https://user-images.githubusercontent.com/65096819/173532468-2d2ab7f9-46c6-4507-b211-2ffd1532c6f0.png)

**Comment by Harry2010410** [comment]
> 安装成功之后应该能在搜索里面找到 LAV Audio ![image](https://user-images.githubusercontent.com/65096819/173532468-2d2ab7f9-46c6-4507-b211-2ffd1532c6f0.png)

好的，多谢，我刚试了下，用potplayer也播放不了，可能是我的电脑声卡出问题了，我更新下驱动试试

**Comment by Harry2010410** [comment]
![image](https://user-images.githubusercontent.com/55910265/173538851-3a14c76d-e664-4660-8c84-ed4522045a6f.png)
找到问题了，机器莫名其妙 扬声器显示未插入，解决办法如上图

**Comment by zhiyiYo** [comment]
> ![image](https://user-images.githubusercontent.com/55910265/173538851-3a14c76d-e664-4660-8c84-ed4522045a6f.png) 找到问题了，机器莫名其妙 扬声器显示未插入，解决办法如上图

👍，如果能正确播放的话我将关闭此 issue，遇到了别的问题可以单独再开一个
