### ISSUE TITLE
歌单功能异常

### ISSUE THREAD

**Issue by Tiper-In-Github** [zhiyiYo/Groove#25]
**Describe the bug**
我在歌单播放页面确定将某歌曲添加到了自建歌单，但是之后查看歌单里面是没有该歌曲的

**To Reproduce**
Steps to reproduce the behavior
1. 通过搜索的方式播放任意音乐
2. 点击左下角进入播放页
3. 在播放页点击显示播放列表
4. 在播放列表右键-添加到-新的播放列表
5. 新建任意名称列表
6. 查看列表为空
7. 再次返回音乐列表，右键-添加到-xxx列表
8. 查看列表为空

**Expected behavior**
添加到列表后，我在列表的页面应该看到该歌曲

**Environment(please complete the following information):**
 - OS: Windows 11 64
 - Python：3.6(本机) / 3.8(虚拟环境)

**Comment by zhiyiYo** [comment]
目前无法添加在线歌曲到自定义播放列表

**Comment by Tiper-In-Github** [comment]
您好，欢迎您致信火毅网络团队。当前人工忙，稍后我们会查看您发的邮件，谢谢合作。--------友情链接----------官方导航站

**Comment by zhiyiYo** [comment]
#21

**Comment by zhiyiYo** [comment]
关于该问题的讨论可以参见：https://github.com/zhiyiYo/Groove/issues/21#issuecomment-1114194549

**Comment by zhiyiYo** [comment]
目前已支持添加任意本地或者在线歌曲到自定义播放列表中。

**Comment by Tiper-In-Github** [comment]
您好，欢迎您致信火毅网络团队。当前人工忙，稍后我们会查看您发的邮件，谢谢合作。--------友情链接----------官方导航站
