### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by guangziteam** [zhiyiYo/Groove#27]
系统：Windows 11 22521
软件版本：1.1.4

视频解析失败（这首歌肯定有视频）
![图片](https://user-images.githubusercontent.com/75152171/179205889-38815145-6d3b-4ebc-93ce-3fe78c1eab49.png)
但最离谱的是，不可以直接播放，但可以下载，并且下载完还可以打开
![图片](https://user-images.githubusercontent.com/75152171/179206110-53dca1bc-b702-4f4f-a6ef-f7dcf6c78ced.png)
![图片](https://user-images.githubusercontent.com/75152171/179206188-dbd6761c-fe13-4138-b643-2ac6cc6477a8.png)

**Comment by guangziteam** [comment]
还有一个小问题，我可以拖着这个返回按钮移动窗口
![图片](https://user-images.githubusercontent.com/75152171/179207010-c8d22fdf-f2b5-4004-b063-842ac8415b56.png)

**Comment by guangziteam** [comment]
又双叒叕有一个问题：
双击最大化按钮，鼠标不松开
慢慢移动鼠标移开最大化按钮
松开鼠标
就会这样：
![图片](https://user-images.githubusercontent.com/75152171/179207237-39dd6930-83fa-49fe-915b-c396c2dd8072.png)

**Comment by zhiyiYo** [comment]
在线视频播放问题无法解决，因为我能做的就是拿到 url 然后给 QMediaPlayer 播放，人家报错说无法播放那就是不能播放

**Comment by zhiyiYo** [comment]
其他几个 bug 晚些时候再修吧

**Comment by guangziteam** [comment]
![QQ录屏20220715183944 00_00_00-00_00_30](https://user-images.githubusercontent.com/75152171/179208370-a820ae43-21c4-439d-ba9f-f0d2229415e2.gif)

**Comment by zhiyiYo** [comment]
建议一个 issue 对应一个 bug，这样我也好 commit

**Comment by guangziteam** [comment]
OK下次分开提交……我觉得分开提交别人看了觉得你程序bug多😅

**Comment by zhiyiYo** [comment]
已修复上述问题，碰到别的问题请单独开个 issue
