### ISSUE TITLE
大佬，请问下程序如何打包的呀 

### ISSUE THREAD

**Issue by LoveChina-3000** [zhiyiYo/Groove#28]
大佬，请教下程序如何打包编译成exe文件的呀？

**Comment by zhiyiYo** [comment]
@LoveChina-3000 
先激活虚拟环境，然后在虚拟环境下面安装 pyinstaller，最后在虚拟环境下使用 pyinstaller 安装
```
conda activate Groove
pip install pyinstaller
cd app
pyinstaller -w -i resource/images/logo/logo.ico Groove.py
```

如果你想减小打包体积的话可以先把 Groove.exe 运行起来，然后多选几个 dll 试着删除他们，弹出 dll 被占用对话框就跳过删除即可，没弹出就说明这些 dll 是多余的

**Comment by LoveChina-3000** [comment]
好的 谢谢，再请教下如果是用pyinstaller的话，那个pro文件有用到吗？多语言问题怎么处理的啊？我看有一个Groove_zh

**Comment by zhiyiYo** [comment]
pro 文件里面的 `SOURCES` 用来说明哪些源文件中会包含需要被翻译的文本，会在 ts 文件（也就是翻译文件）生成对应的翻译条目，因为我用的是 VSCode 来开发的项目，所以装了一些 qt 相关的插件，然后只要右击 pro 文件，选择生成 ts 文件，就会根据 `TRANSLATIONS` 生成翻译源文件（实际上为 xml 格式的），接着使用 Qt Linguist 软件打开 ts 文件，在这里面可以进行翻译工作，最后导出为 qm 二进制翻译文件，关于插件可以参见我的博客 [如何在 VS Code 中搭建 Qt 开发环境](https://www.cnblogs.com/zhiyiYo/p/14877952.html)，关于 Qt Linguist 的使用参见知乎 [《快速掌握PyQt5》第二十九章 国际化](https://zhuanlan.zhihu.com/p/75650992)，只要添加下述代码就能使用翻译文件了：
```python
translator = QTranslator()
translator.load(QLocale.system(), ":/i18n/Groove_")
app.installTranslator(translator)
```

**Comment by LoveChina-3000** [comment]
非常感谢大佬 谢谢~
