### ISSUE TITLE
Ability to add lyrics to the file - to synchronize lyrics with song

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#29]
Ability to add lyrics to the file - to synchronize lyrics with song

**Comment by zhiyiYo** [comment]
@messagebeliever2022 
This feature has been implemented. You can embed lyrics to audio file when save song information (need be enabled in setting interface). Groove now can also read embedded lyrics from audio file.

**Comment by zhiyiYo** [comment]
@messagebeliever2022 
You can now embed lyrics directly into the audio file through the menu.
![image](https://user-images.githubusercontent.com/65096819/192100119-0a279510-e788-429e-8a56-b8ab90897c41.png)

**Comment by messagebeliever2022** [comment]
Thank you
