### ISSUE TITLE
Add button is not working to add audio files in Windows 10

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#31]
Hi,

Add button is not working to add audio files in Windows 10
Is there a way to enable log or is it possible for you to verify in windows 10? if you don't have you can install via virtual box and try
Mine is 64-bit Windows 10
Add to shows the playlist name but no popup appears to add the song

Thanks

**Comment by messagebeliever2022** [comment]
![image](https://user-images.githubusercontent.com/112235944/192034534-84fb1ecc-94a1-436b-ae2a-1e53324ea415.png)

**Comment by zhiyiYo** [comment]
There are no songs in your New Playlist, so you cannot add its songs to the Test playlist.

**Comment by messagebeliever2022** [comment]
I understand no song in the playlist. Basically how to create a song and add to the playlist. It should be separate and dependent on one another. I will create many play list and add the songs to the list.

**Comment by zhiyiYo** [comment]
I don't understand what you mean. Do you want to ask how to add songs to a playlist? If so, please refer to the adding method demonstrated in the gif of readme.

**Comment by messagebeliever2022** [comment]
The gif shows about adding a folder and not a file. I am requesting for a file to be added. Also going to the settings fine and an option in the play list would be very easy. Please kindly consider. Also the gif speed is very fast. make it little slower if possible

**Comment by zhiyiYo** [comment]
At present, there are some problems with the design of the playlist function. I will upgrade the function of the playlist later.

**Comment by zhiyiYo** [comment]
@messagebeliever2022 
You can now add any local or online songs to custom playlist. You can also download the online songs on custom playlist.
![image](https://user-images.githubusercontent.com/65096819/192527663-3cdc4b6c-6ca8-43bf-a39c-2b33f5f7ac0f.png)

**Comment by messagebeliever2022** [comment]
Thanks a lot
