### ISSUE TITLE
No option to sychronize lyrics and steps are not clear

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#32]
Hi,

I tried to synchronize a lyrics with an audio file.

missing
#1 - where to place the lyrics?
#2 - format of the lyrics file?
#3 - how to play the song with the  lyrics

Thanks

**Comment by messagebeliever2022** [comment]
![image](https://user-images.githubusercontent.com/112235944/192034427-788ce8d3-bbff-4e00-a24d-a235feff4887.png)

**Comment by zhiyiYo** [comment]
1. You can find the lyrics file in `app/cache/lyric` folder.
2. The suffix of lyrics file should be `.json` or `.lrc`
3. You can open the song info edit dialog and click save button to embed lyrics to audio file. Groove will select the appropriate lyrics file automaticly

**Comment by messagebeliever2022** [comment]
1. No file exist in the folder
2. suffix is fine
3. Please add few screenshot to understand how to navigate
4. I already have lyrics for my mp3 songs which i want to sychronize

**Comment by zhiyiYo** [comment]
Please upload your lyrics file which failed to parse.

**Comment by messagebeliever2022** [comment]
Tried the following ways but none worked...

Add hh:mm:ss forward kind of delimiter for easy use

Option#1 (ss)
{"line":"தேவனே உம்மை நம்பினோர்‌ மாண்டதில்லை","time":33000},
{"line":"உம்‌ வழிகள்‌ ஆராய்ந்து முடியாதவை","time":47000},
{"line":"உம்‌ வார்த்தைகள்‌ ஜீவனும்‌ பெலனானவை","time":52000},
{"line":"ஊழியம்‌ செய்திடும்‌ சொந்தக்‌ குமாரனை‌","time":130000}

Option #2 (ss)
[33000] தேவனே உம்மை நம்பினோர்‌ மாண்டதில்லை
[47000] உம்‌ வழிகள்‌ ஆராய்ந்து முடியாதவை
[52000] உம்‌ வார்த்தைகள்‌ ஜீவனும்‌ பெலனானவை
[130000] ஊழியம்‌ செய்திடும்‌ சொந்தக்‌ குமாரனை‌

Option #2 (hh:mm:ss)
[00:00:33] தேவனே உம்மை நம்பினோர்‌ மாண்டதில்லை
[00:00:47] உம்‌ வழிகள்‌ ஆராய்ந்து முடியாதவை
[00:00:52] உம்‌ வார்த்தைகள்‌ ஜீவனும்‌ பெலனானவை
[00:01:30] ஊழியம்‌ செய்திடும்‌ சொந்தக்‌ குமாரனை‌

**Comment by zhiyiYo** [comment]
@messagebeliever2022 
if the format of lyrics file is `.lrc`, the the structure should be like **[mm:ss.xx]**, where mm is minutes, ss is seconds and xx is hundredths of a second. You can refer to https://en.wikipedia.org/wiki/LRC_(file_format) for more information about `.lrc` format.
```
[ti:Let's Twist Again]
[ar:Chubby Checker oppure  Beatles, The]
[au:Written by Kal Mann / Dave Appell, 1961]
[al:Hits Of The 60's - Vol. 2 – Oldies]

[00:12.00]Naku Penda Piya-Naku Taka Piya-Mpenziwe
[00:15.30]Some more lyrics
[00:15.30]更多歌词 # you can duplicate the time tag to add traslation
```

if the format is `.json`, then the structure should be like **"seconds":["orginal lyric"]** or **"seconds":["orginal lyric", "translation lyric"]**
```json
{
    "1.86": [
        "微熱 - Aiko "
    ],
    "3.7": [
        "词：aiko"
    ],
    "6.49": [
        "曲：aiko"
    ],
    "28.22": [
        "今夜も必ず連絡するね",
        "今夜也一定会和我联系"
    ],
    "34.36": [
        "昼も夜も抱きしめて",
        "又能相拥一夜"
    ],
}
```

**Comment by messagebeliever2022** [comment]
Thank You
