### ISSUE TITLE
Few sample lyrics structure/format with comments should be part of the examples folder

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#34]
Hi,

It would be really helpful to have an example folder and paste the necessary sample files which are related to the groove. 

example, sample lyrics structure/format which can be synchronized with the music

Thanks

**Comment by zhiyiYo** [comment]
I will add a markdown file which explains the structure of lyricd file to the docs folder later.

**Comment by messagebeliever2022** [comment]
yes, please do so else any user will struggle to figure out on how it has to be
