### ISSUE TITLE
Edit Option to Edit the Lyrics via the application

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#35]
Hi,

Need an Edit Option to Edit the Lyrics via the application

Thanks

**Comment by zhiyiYo** [comment]
I will consider your suggestion. And I'm a student at present, maybe I don't have much time to implement all feature requests.

**Comment by zhiyiYo** [comment]
1. search lav audio configuration
![image](https://user-images.githubusercontent.com/65096819/193188421-d69acfc8-25be-4395-87f1-c9eea31d04f2.png)

2. configure in the mixing tab
![image](https://user-images.githubusercontent.com/65096819/193188444-30bdb91a-8a76-499d-8ef6-5c659f25fad9.png)
