### ISSUE TITLE
Is Type-ahead search of file name is possible for local songs

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#36]
Hi,

I have added many songs to the list and on search the results are coming for local and online

1. How to disable the online songs which i don't need?
2. Is it possible to provide type-ahead search for local song i.e show results on typing

![image](https://user-images.githubusercontent.com/112235944/192124895-137daedd-076f-4872-a4aa-9a1a8e8db430.png)

Thanks

**Comment by zhiyiYo** [comment]
1. I will add an option to disable searching online songs.
2. I don't plan to implement this function, because the style of the pull-down menu is ugly

**Comment by zhiyiYo** [comment]
You can disable the online search by setting the number of online songs displayed to 0 in the setting interface.
![image](https://user-images.githubusercontent.com/65096819/192127601-71580438-e961-4132-ad14-6ad8da7eb2f1.png)
