### ISSUE TITLE
Sort Option like in Datatable

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#38]
Hi,

Is it possible to add sort option in Headers in datatables or somehow to sort by

1. Song Name
2. Date Added
3. Artist Name

![image](https://user-images.githubusercontent.com/112235944/192125013-0f4822e8-92dd-48d5-a76e-a7a6cca91c90.png)

Thanks

**Comment by zhiyiYo** [comment]
You can click the sort by button to sort.
![image](https://user-images.githubusercontent.com/65096819/192125182-8776fb5b-a0e1-4a71-ac3a-a70e78e2c962.png)
