### ISSUE TITLE
Equalizer and Presets

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#39]
Hi,

It will be really good if we have equalizer and presets of setup with different choosing via option...

Any basic or anything would be fine....Below are few examples

![image](https://user-images.githubusercontent.com/112235944/193119817-14867b6e-f7c9-4773-befc-b6ee924fe330.png)

![image](https://user-images.githubusercontent.com/112235944/193119892-9ae49e7b-3762-4381-8cc3-5cb67af9fa6b.png)

![image](https://user-images.githubusercontent.com/112235944/193120204-33428031-0245-4d14-85d7-d98215e9142c.png)

![image](https://user-images.githubusercontent.com/112235944/193120351-7422e5c5-ddef-4684-bf28-1f6d2007f149.png)

Thanks

**Comment by messagebeliever2022** [comment]
http://antonkhorev.github.io/webaudio-starter/en/base/
https://github.com/cwilso/wubwubwub/blob/MixTrack/js/tracks.js#L189-L207

**Comment by zhiyiYo** [comment]
Lav filters are responsible for decoding and playing audio, and I can't influence them. You can configure the equalizer in the configuration interface of lav filters.

**Comment by messagebeliever2022** [comment]
Can you please help with the screenshot or menu or steps to configure the LAV filters and not aware of it?

**Comment by messagebeliever2022** [comment]
Any steps or screenshots would be helpful

**Comment by zhiyiYo** [comment]
1. search lav audio configuration
![image](https://user-images.githubusercontent.com/65096819/193188421-d69acfc8-25be-4395-87f1-c9eea31d04f2.png)

2. configure in the mixing tab
![image](https://user-images.githubusercontent.com/65096819/193188444-30bdb91a-8a76-499d-8ef6-5c659f25fad9.png)
