### ISSUE TITLE
Is it possible to provide support for .rm files as well without affecting any functionality?

### ISSUE THREAD

**Issue by messagebeliever2022** [zhiyiYo/Groove#40]
Hi,

I have many files in .rm format (real media player formats). Is it possible to provide support for .rm files as well without affecting any functionality?

Pls kindly check if that can be added to the supported list

Thanks

**Comment by zhiyiYo** [comment]
There are no aufio files in .rm format on my computer. Can you upload some samples for me to test？

**Comment by messagebeliever2022** [comment]
Uploaded the .rm and .ram files for your kind testing - https://easyupload.io/dni2l9

**Comment by messagebeliever2022** [comment]
.rm and .ram - two formats needs to be supported.

**Comment by zhiyiYo** [comment]
Please upload the zip file here, because I can't download the file on easyupload.io.

**Comment by lovertech2022** [comment]
[rm and ram files.zip](https://github.com/zhiyiYo/Groove/files/9685808/rm.and.ram.files.zip)

**Comment by messagebeliever2022** [comment]
[rm and ram files.zip](https://github.com/zhiyiYo/Groove/files/9685826/rm.and.ram.files.zip)

**Comment by messagebeliever2022** [comment]
Attached the files for your reference

**Comment by zhiyiYo** [comment]
It's 23:46 midnight here, so I'll test these files tomorrow.

**Comment by messagebeliever2022** [comment]
sure. thank you

**Comment by zhiyiYo** [comment]
Currently I can't read the tag information of rm and ram files, so I don't plan to support these two outdated file formats for now.

**Comment by messagebeliever2022** [comment]
Please refer the below which recognizes the tag info ... Just FYI

https://github.com/exiftool/exiftool
https://exiftool.org/TagNames/Real.html  (https://exiftool.org/)
https://filehippo.com/download_real_alternative/

Please let me know if you need more examples

**Comment by passionate2023** [comment]
Is it possible to make them play without tag or more details from the file?
