### ISSUE TITLE
Likes Or Favourites Songs Column Or Option as one of the menu to add favourite songs

### ISSUE THREAD

**Issue by lovertech2022** [zhiyiYo/Groove#42]
Hi,

Can you please provide an option or menu to add Likes Or Favourites Songs..
It has to been displayed with favourite icon in the left menu?

![image](https://user-images.githubusercontent.com/114723135/193227719-116bfbac-ca1d-4c61-9616-85bded2f613f.png)

Thanks

**Comment by zhiyiYo** [comment]
I don't understand what you mean. You can add songs to the playlist through the context menu.
![image](https://user-images.githubusercontent.com/65096819/193252276-a24824f3-c93e-4b56-84ac-483d5f5cb161.png)

**Comment by lovertech2022** [comment]
Playlist Icon is different from Favourites. I may have 20 playlist but i may like one among each playlist....

Favourites or likes with a beautiful icon which should be added with a click like bookmark a page or click favourites in stackoverflow.....not with too many steps or right click...

Just a single click of a icon in the song. The song should be displayed in the favourites menu

**Comment by zhiyiYo** [comment]
So why not create a playlist named Favorites? And I don't think there is extra space on the song card for adding the icon.

**Comment by lovertech2022** [comment]
Can you have some icons - pre-defined to get it attached to the playlist menu, so that it would be easy and achievable? What do you say

**Comment by zhiyiYo** [comment]
I will consider adding a default Favorites playlist later. Thank you for your advice.
