### ISSUE TITLE
Font Option To Change The Fonts Of Lyrics or Song Title

### ISSUE THREAD

**Issue by gitexp2050** [zhiyiYo/Groove#44]
Hi,

Is it possible to provide an option to change the font of the lyrics or song title both permanently as well temporary ?

Also the font size

Attached an image from another player which has the font option just for reference

![image](https://user-images.githubusercontent.com/115112320/194468044-73577c19-e85a-434b-bda9-25a4df7a685a.png)

Thank You.

**Comment by zhiyiYo** [comment]
Do you mean to change the font of lyrics in the playing interface?

**Comment by gitexp2050** [comment]
yes, it is possible to change dynamically or permanently ....Song Lyrics as well as Song Name/Title

**Comment by zhiyiYo** [comment]
At present, fonts are written in qss.  I will add the feature of adjusting lyrics fonts later. But I don't know why you need to adjust the font of the song title🤔

**Comment by zhiyiYo** [comment]
Groove will automatically zoom the interface according to the system settings.

**Comment by gitexp2050** [comment]
Dynamic Font Changing is more comfortable for all users in general instead of permanent setting.

**Comment by zhiyiYo** [comment]
I will consider adding a option to adjust the zoom ratio

**Comment by zhiyiYo** [comment]
At present, the feature of manually adjusting the interface zoom has been completed
