### ISSUE TITLE
Convert files option if possible

### ISSUE THREAD

**Issue by gitexp2050** [zhiyiYo/Groove#46]
Hi,

Whatever the format the file is if there is a convert files option to convert. it would be great...
example, mp4 to mp3 etc.,

Just 1 or 2 files will do the magic for you

https://github.com/adityashrm21/Video-to-audio-converter
https://github.com/Blue9/AudioJack
https://github.com/dopstar/ftransc
https://github.com/Top-Dog/Python-MP4-to-MP3-Converter/tree/master/Python-MP4-to-MP3-Converter/Python-MP4-to-MP3-Converter

Thank you

**Comment by zhiyiYo** [comment]
This is a music player, not music format factory.

**Comment by gitexp2050** [comment]
The user can import the files which they like to import but conversion has to be made in different websites and sometimes it has malware too. if this is doable it would be really helpful or any possible of integration with existing conversion factory

**Comment by zhiyiYo** [comment]
Groove currently supports many popular audio file formats. It is unnecessary to add format conversion function.

**Comment by gitexp2050** [comment]
Is it possible to add a conversion for .rm or .ram or atleast support these 2 formats?

**Comment by gitexp2050** [comment]
Is it possible to add a conversion for .rm or .ram or atleast support these 2 formats?
