### ISSUE TITLE
歌词无法解析(.lrc)

### ISSUE THREAD

**Issue by 745404527** [zhiyiYo/Groove#49]
**Describe the bug**
**歌词文件**无法解析
![bug](https://user-images.githubusercontent.com/61670738/200342639-f5fe44d7-3aec-4b16-98da-39bd029f6d77.PNG)

**To Reproduce**
1.使用外部歌词文件
2.歌词无法解析

**Expected behavior**
歌词正常显示

**Environment(please complete the following information):**
 - OS: Win10
 - DPI scaling: 125%
 - Ver : 1.2.1

**Additional context**
这是无法导入的歌词文件和其相对应的音频，可以尝试复现一下，我没看出来啥问题
[music.zip](https://github.com/zhiyiYo/Groove/files/9952823/music.zip)

**Comment by zhiyiYo** [comment]
应该是我写的歌词解析器的问题，在  parser.py 的第 80 行不小心把 "\r\n" 写死在里面了

**Comment by zhiyiYo** [comment]
@745404527 
我已经把修改推送到 github 了，你可以 pull 下来测试一下，我这边现在是没有问题的

**Comment by zhiyiYo** [comment]
没必要吧，而且 pyside 少了很多函数，导致我用的PyQt-Frameless-Window无边框窗口在linux用不了
