### ISSUE TITLE
在 Windows 7 上关闭、最小化等按钮错位

### ISSUE THREAD

**Issue by wuxian425** [zhiyiYo/Groove#50]
**Describe the bug**
如题，在 Windows7 的关闭等按钮发生错位。
![image](https://user-images.githubusercontent.com/82699919/201480421-931fb018-743d-4f35-9234-8875d430805a.png)
（见图右上角） 

**To Reproduce**
Steps to reproduce the behavior(you can use GIF to demonstrate :)
1. 将鼠标移到右上角。
2. 装饰的关闭按钮等对不上实际的关闭按钮。

**Expected behavior**
可正常进行关闭、最大化、最小化以及窗口化等功能。

**Environment(please complete the following information):**
 - OS: Win7 （未开启 Aero）
 - DPI scaling: 正常
 - Version: 1.2.1

**Additional context**
![image](https://user-images.githubusercontent.com/82699919/201480683-6c3a385d-1f9d-46e8-a2f0-142a62566db0.png)
另外也导致了这个问题...

**Comment by zhiyiYo** [comment]
我这里没有 windows7 的系统，可能测试不了

**Comment by zhiyiYo** [comment]
我把修改后的代码 push 到 dev 分支上了，可以帮忙测试一下吗？

**Comment by wuxian425** [comment]
在开启 Aero 及关闭 Aero 时鼠标悬浮到按钮上面皆会把原生的按钮调出来，不过开启时菜单是正常的，关闭 Aero 时开启菜单会把原生边框调出来（如下图）
![image](https://user-images.githubusercontent.com/82699919/201501071-174ae57b-2fc5-4985-8e5a-837d202a38d3.png)

**Comment by zhiyiYo** [comment]
如果没有启用设置界面的亚克力背景，还会出现系统边框吗
![image](https://user-images.githubusercontent.com/65096819/201501331-ecdadb76-105e-4e4f-a342-ddf47c638a5a.png)

**Comment by wuxian425** [comment]
> 如果没有启用设置界面的亚克力背景，还会出现系统边框吗 ![image](https://user-images.githubusercontent.com/65096819/201501331-ecdadb76-105e-4e4f-a342-ddf47c638a5a.png)

本来就没有开启

**Comment by zhiyiYo** [comment]
可能是 [PyQt-Frameless-Window](https://github.com/zhiyiYo/PyQt-Frameless-Window) 包的问题，运行这个仓库的 demo.py 会出现系统边框吗？🤔

**Comment by wuxian425** [comment]
会的（如下图）
 ![image](https://user-images.githubusercontent.com/82699919/201501888-726dd411-038d-46fa-9bdd-51a941cee56e.png)

话说不在虚拟环境运行（我不清楚怎么用，就直接装完依赖运行了）的Groove音乐没办法播放音乐是正常的嘛？

**Comment by zhiyiYo** [comment]
无边框窗口的问题确实有点诡异，我再排查排查

**Comment by zhiyiYo** [comment]
@wuxian425 
可以帮忙录制一个 PyQt-Frameless-Window 的 bug 演示视频吗，我分析一下问题出在哪

**Comment by wuxian425** [comment]
> @wuxian425 可以帮忙录制一个 PyQt-Frameless-Window 的 bug 演示视频然后在 [PyQt-Frameless-Window](https://github.com/zhiyiYo/PyQt-Frameless-Window) 提个新 issue 吗，我分析一下问题出在哪

好的

**Comment by zhiyiYo** [comment]
我把最新代码 push 到 dev 分支了，可以帮忙测试一下吗？

**Comment by wuxian425** [comment]
> 我把最新代码 push 到 dev 分支了，可以帮忙测试一下吗？

![image](https://user-images.githubusercontent.com/82699919/201530687-79e8babf-7e92-47f2-a2d3-97cf64f28b2d.png)
非 Aero 在开启菜单栏时会变酱紫

###### 刚刚切换 Aero 的时候 Chrome 闪退了，电脑真是个玄学的东西

**Comment by zhiyiYo** [comment]
这尼玛也太玄学了，不开菜单栏的话会导致系统边框出现吗

**Comment by wuxian425** [comment]
> 这尼玛也太玄学了，不开菜单栏的话会导致系统边框出现吗

不会

**Comment by wuxian425** [comment]
这玩意只要软件界面上点一下就解决了，应该无伤大雅

**Comment by zhiyiYo** [comment]
暂时解决不了此问题😕
