### ISSUE TITLE
在最大化时非播放界面的状况，点击更多操作按钮菜单不显示。

### ISSUE THREAD

**Issue by wuxian425** [zhiyiYo/Groove#51]
**Describe the bug**
在最大化时非播放界面的状况，点击更多操作按钮菜单不显示（不在屏幕显示范围）。

**To Reproduce**
在非播放界面且最大化的状况点击更多操作按钮

**Expected behavior**
在合理区域跳出更多操作的菜单

**Environment(please complete the following information):**
 - OS: Windows 7 Aero Mode
 - DPI scaling: Default
 - Version: 1.2.1

**Additional context**
![image](https://user-images.githubusercontent.com/82699919/201512860-ad6fd814-40fa-472a-9e17-3dc57c7f7dea.png)
（正常）
![image](https://user-images.githubusercontent.com/82699919/201512869-155f1ae2-f2d1-4c30-9729-8abe00969826.png)
（已点击，在 Focus 状态 ）

**Comment by zhiyiYo** [comment]
感谢反馈，之后会修复这个 bug 的

**Comment by zhiyiYo** [comment]
这个问题在最新的 dev 分支已经解决，可以 pull 下来尝试一下
