### ISSUE TITLE
上下滚动音乐列表后左右移动鼠标引发实体挤压会导致鼠标抖动

### ISSUE THREAD

**Issue by 745404527** [zhiyiYo/Groove#53]
**Describe the bug**
上下滚动 **音乐列表(或者歌词)** 后左右移动鼠标引发实体挤压会导致 **鼠标抖动**

**To Reproduce**
https://user-images.githubusercontent.com/61670738/201526730-2b30d218-59d4-4a10-b877-bc14bb43f588.mp4

**Expected behavior**
鼠标可以正常滚动

**Environment(please complete the following information):**
 - OS: Win10 (Arch Linux 经测试同样会引发这个bug)
 - DPI scaling: 125%

**Additional context**
我前年做滚动的时候也尝试解决过这玩意，最后没啥好办法，如果解决希望可以让我参考参考 :)

**Comment by zhiyiYo** [comment]
我给 app/components/widgets/scroll_area.py 的 `ScrollArea` 类添加了一个滚轮槽函数，这样滚动过程中才能刷新歌曲卡的 hover 状态，我这里滚动的时候不会出现鼠标抖动：
```python

class ScrollArea(QScrollArea):
    """ A scroll area which can scroll smoothly """

    def __init__(self, parent=None):
        # 省略部分代码
        self.verticalScrollBar().valueChanged.connect(self.__fakeMoveMouse)

    def __fakeMoveMouse(self):
        """ fake move mouse """
        pos = QCursor.pos()
        QCursor.setPos(pos + QPoint(0, 1))
        QApplication.processEvents()
        QCursor.setPos(pos)
```

**Comment by wuxian425** [comment]
> 我给 app/components/widgets/scroll_area.py 的 `ScrollArea` 类添加了一个滚轮槽函数，这样滚动过程中才能刷新歌曲卡的 hover 状态，我这里滚动的时候不会出现鼠标抖动：
> 
> ```python
> class ScrollArea(QScrollArea):
>     """ A scroll area which can scroll smoothly """
> 
>     def __init__(self, parent=None):
>         # 省略部分代码
>         self.verticalScrollBar().valueChanged.connect(self.__fakeMoveMouse)
> 
>     def __fakeMoveMouse(self):
>         """ fake move mouse """
>         pos = QCursor.pos()
>         QCursor.setPos(pos + QPoint(0, 1))
>         QApplication.processEvents()
>         QCursor.setPos(pos)
> ```

我这边也有抖动的行为，还以为是鼠标坏了
录屏帧率太低了看不了

**Comment by wuxian425** [comment]
> > > 我给 app/components/widgets/scroll_area.py 的 `ScrollArea` 类添加了一个滚轮槽函数，这样滚动过程中才能刷新歌曲卡的 hover 状态，我这里滚动的时候不会出现鼠标抖动：
> > > ```python
> > > class ScrollArea(QScrollArea):
> > >     """ A scroll area which can scroll smoothly """
> > > 
> > >     def __init__(self, parent=None):
> > >         # 省略部分代码
> > >         self.verticalScrollBar().valueChanged.connect(self.__fakeMoveMouse)
> > > 
> > >     def __fakeMoveMouse(self):
> > >         """ fake move mouse """
> > >         pos = QCursor.pos()
> > >         QCursor.setPos(pos + QPoint(0, 1))
> > >         QApplication.processEvents()
> > >         QCursor.setPos(pos)
> > > ```
> > 
> > 
> > 我这边也有抖动的行为，还以为是鼠标坏了
> > 录屏帧率太低了看不了
> 
> 没这么低吧……

网页录屏

**Comment by wuxian425** [comment]
> 我给 app/components/widgets/scroll_area.py 的 `ScrollArea` 类添加了一个滚轮槽函数，这样滚动过程中才能刷新歌曲卡的 hover 状态，我这里滚动的时候不会出现鼠标抖动：
> 
> ```python
> class ScrollArea(QScrollArea):
>     """ A scroll area which can scroll smoothly """
> 
>     def __init__(self, parent=None):
>         # 省略部分代码
>         self.verticalScrollBar().valueChanged.connect(self.__fakeMoveMouse)
> 
>     def __fakeMoveMouse(self):
>         """ fake move mouse """
>         pos = QCursor.pos()
>         QCursor.setPos(pos + QPoint(0, 1))
>         QApplication.processEvents()
>         QCursor.setPos(pos)
> ```

### [***手机录像***](http://drive.paimon.cloud/s/eRFN)

**Comment by zhiyiYo** [comment]
现在有点怀疑是不是操作系统的问题，待会儿在 Win10 试试

**Comment by zhiyiYo** [comment]
确实是 `__fakeMoveMouse()` 惹的祸，左右移动光标之后导致保存的 `pos` 和实际值不同，进而引发抖动

**Comment by zhiyiYo** [comment]
@745404527 @wuxian425 
刚才改了一下 `__fakeMouseMove()`，算是较好地解决了抖动问题，可以 pull 下来试试
