### ISSUE TITLE
播放本地音乐时持续报错

### ISSUE THREAD

**Issue by wuxian425** [zhiyiYo/Groove#55]
**Describe the bug**
如题，在播放本地音乐时疯狂的报错，然后你什么也干不了。

**To Reproduce**
把音乐加入媒体库
播放音乐

**Expected behavior**
正常播放

**Environment(please complete the following information):**
 - OS: Windows 7 （64bit, 繁体中文版）
 - DPI scaling: Default
 - Version: 1.2.1

**Additional context**
[record.webm](https://user-images.githubusercontent.com/82699919/201530062-3e88478d-3f60-4f02-b486-31bc9b978608.webm)
真的会疯掉.png

**Comment by wuxian425** [comment]
原来真有报错（雾
```
  File "View\main_window\main_window.py", line 699, in updateWindow

IndexError: list index out of range
```

**Comment by zhiyiYo** [comment]
我的 main_window.py 的 699 行是 `signalBus.playBySongInfoSig.emit(songInfo)`，应该不会报下标越界错误
![image](https://user-images.githubusercontent.com/65096819/201531009-785e49cc-c730-4d3f-b16c-c670b35ef0d4.png)

而且不给我媒体库的话我也复现不了这个问题

**Comment by wuxian425** [comment]
> 我的 main_window.py 的 699 行是 `signalBus.playBySongInfoSig.emit(songInfo)`，应该不会报下标越界错误 ![image](https://user-images.githubusercontent.com/65096819/201531009-785e49cc-c730-4d3f-b16c-c670b35ef0d4.png)
> 
> 而且不给我媒体库的话我也复现不了这个问题

媒体库 [在这儿](http://drive.paimon.cloud/s/2Jc2)

**Comment by zhiyiYo** [comment]
仍然无法复现此问题，可以从头录个屏吗

**Comment by supersu097** [comment]
跟我这个[issue](https://github.com/zhiyiYo/Groove/issues/47#issuecomment-1277296707) 看起来很像呀~

**Comment by supersu097** [comment]
> 仍然无法复现此问题，可以从头录个屏吗

老哥，要不那你看弄个Windows 10虚拟机试一下，可能你的本地开发环境太完备了，现在看来不止我一个人遇到本地播放疯狂报错了~

**Comment by zhiyiYo** [comment]
问题是你们两个人报的错不一样呀

**Comment by supersu097** [comment]
> 

嗯嗯，确实不一样，估计要想复现就要开发者你和我们都弄个虚拟机装win10或7，然后再搞个python虚拟环境了，实在不行的话等我年底最后几天没事干了好好打个断点调试一下

**Comment by zhiyiYo** [comment]
@supersu097 
我之前在 Win10 电脑上测试过也不会有这些问题

**Comment by supersu097** [comment]
> 

是你本地的开发环境么，有试过在一个纯净的虚拟机里面运行么

**Comment by zhiyiYo** [comment]
用的别人的电脑

**Comment by zhiyiYo** [comment]
@wuxian425 
> 我的 main_window.py 的 699 行是 signalBus.playBySongInfoSig.emit(songInfo)，应该不会报下标越界错误

感觉你用的代码不是最新的

**Comment by wuxian425** [comment]
> @wuxian425
> 
> > 我的 main_window.py 的 699 行是 signalBus.playBySongInfoSig.emit(songInfo)，应该不会报下标越界错误
> 
> 感觉你用的代码不是最新的

我等等用最新的 Dev 版再试试

**Comment by wuxian425** [comment]
> @wuxian425
> 
> > 我的 main_window.py 的 699 行是 signalBus.playBySongInfoSig.emit(songInfo)，应该不会报下标越界错误
> 
> 感觉你用的代码不是最新的

可能是之前闪退导致的，现在没有了

**Comment by wuxian425** [comment]
可能和 #56 有关系？
