### ISSUE TITLE
支持搜索子文件夹

### ISSUE THREAD

**Issue by wuxian425** [zhiyiYo/Groove#57]
**Is your feature request related to a problem? Please describe.**
我是使用一个文件夹包着另外几个小文件夹（歌手分类），如果要把它们全部加入媒体库需要很长一段时间

**Describe the solution you'd like**
支持搜索子文件夹

**Describe alternatives you've considered**
无。

**Additional context**
无。

**Comment by zhiyiYo** [comment]
有点麻烦，下次一定😕

**Comment by wuxian425** [comment]
噔 噔 咚

**Comment by zhiyiYo** [comment]
目前已添加递归搜索子文件的功能
