### ISSUE TITLE
点击多次搜索键才搜索出在线音乐结果

### ISSUE THREAD

**Issue by wuxian425** [zhiyiYo/Groove#58]
如题，我不知道这是个 Bug 还是网络问题，如果是网络问题能否加上一个超时时自动重试数遍？

**Comment by zhiyiYo** [comment]
酷我接口有点问题，经常504，如果给 api 少传一个 reqId 参数，可以稳定一些，但是就拿不到年份信息了，很头疼

**Comment by wuxian425** [comment]
> 酷我接口有点问题，经常504，如果给 api 少传一个 reqId 参数，可以稳定一些，但是就拿不到年份信息了，很头疼

504 的时候可以自动重试嘛（

**Comment by zhiyiYo** [comment]
重试大概率也是504，只能看看酷我会不会把这个接口修好，网页上也经常搜不到东西，很离谱就是了

**Comment by zhiyiYo** [comment]
目前考虑504后重新发送一次没有年份信息的请求

**Comment by zhiyiYo** [comment]
@wuxian425 
目前已添加重试功能，你可以 pull 下来试试
