### ISSUE TITLE
想问下有没有遇到过在不同分辨率下界面显示不一致的情况

### ISSUE THREAD

**Issue by niuzijia** [zhiyiYo/Groove#60]
想问下UP，有没有遇到过在不同分辨率下界面显示不一致的情况，我编写了一个界面，在22寸显示器上显示的很好，字体，图形大小都很合适，等到14寸笔记本上显示，就会出现图形太小，字体过小的情况，谷歌搜索后，加入如下代码，还是不行
![image](https://user-images.githubusercontent.com/68538774/203449954-a6335382-de24-4c28-a585-32142fa9e206.png)
请问下，您有遇到过这种问题么，有没有好的解决方案

**Comment by zhiyiYo** [comment]
应该是另外一台电脑的dpi缩放不一样导致的

**Comment by zhiyiYo** [comment]
你现在用的是pyqt6还是pyqt5，如果是6的话默认启用了界面dpi缩放

**Comment by zhiyiYo** [comment]
如果是 PyQt5 的话应该加上下面这一行代码
```python
QApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
```

**Comment by niuzijia** [comment]
> 如果是 PyQt5 的话应该加上下面这一行代码
> 
> ```python
> QApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
> ```

铁子，太厉害了，界面现在正常了，最终的代码如下
```
if __name__ == '__main__':
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)
    QApplication.setHighDpiScaleFactorRoundingPolicy(QtCore.Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    app = QApplication(sys.argv)
    demo = MainUi()
    demo.show()
    sys.exit(app.exec_())
```

只是为什么在pycharm里会提示如下警示呢，我看QT类里是有这个类属性的
![image](https://user-images.githubusercontent.com/68538774/203456247-0fbefc58-d4e5-4fc8-abf8-bfc102cd2d9e.png)

![image](https://user-images.githubusercontent.com/68538774/203456319-a4e18ed2-d79c-40e2-a05e-31d66ef2f283.png)

**Comment by niuzijia** [comment]
好的，多谢老铁

**Comment by niuzijia** [comment]
建议贴一个打赏二维码😘

**Comment by zhiyiYo** [comment]
喜欢的话点个 star 就行，没必要打赏🙂
