### ISSUE TITLE
这里没有可显示的内容。请选择其他筛选器

### ISSUE THREAD

**Issue by Anchor1566** [zhiyiYo/Groove#61]
**Describe the bug**
您好，你做的好好看呀！！非常想要向您学习！！我在打开的时候，gui界面会显示这个，是因为我lav没有安装正确还是什么呀。很感谢您的回答

**Comment by zhiyiYo** [comment]
俺的图图呢？

**Comment by Anchor1566** [comment]
哈哈哈哈图图来啦
您做的真的好好！如果您有时间，我想您可以在bilibili上上传一个视频，应该会有更多人看见您的作品。到时候通知我呀，我一定一键三连＼(`Δ’)／



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月26日(周六) 晚上9:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhiyiYo/Groove] 这里没有可显示的内容。请选择其他筛选器 (Issue #61)




 
俺的图图呢？

**Comment by zhiyiYo** [comment]
还是没图啊？

**Comment by zhiyiYo** [comment]
我懂你的意思了，你是没有在设置界面中添加歌曲文件夹，歌曲列表里面没有歌曲所以显示 “这里没有可显示的内容。请选择其他筛选器” 的提示，你可以参考动图里面的操作添加歌曲文件夹

**Comment by Anchor1566** [comment]
好滴！谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月26日(周六) 晚上10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhiyiYo/Groove] 这里没有可显示的内容。请选择其他筛选器 (Issue #61)




 
我懂你的意思了，你是没有在设置界面中添加歌曲文件夹，歌曲列表里面没有歌曲所以显示 “这里没有可显示的内容。请选择其他筛选器” 的提示，你可以参考动图里面的操作添加歌曲文件夹

**Comment by zhiyiYo** [comment]
> 您做的真的好好！如果您有时间，我想您可以在bilibili上上传一个视频，应该会有更多人看见您的作品。到时候通知我呀，我一定一键三连＼(`Δ’)／

我有在自己的博客里面提到这个软件，所以没必要在 B 站宣传，毕竟会注意这个软件的大都是程序员
