### ISSUE TITLE
Move forward/backward option with seconds for transcription

### ISSUE THREAD

**Issue by javadevelopment4** [zhiyiYo/Groove#65]
Hi,

I would play the audio -- sometimes i want to move forward or backward few seconds

Please add the following if possible
a. add a configuration to specify no of seconds for both backward and forward separately
b. add a shortcult as well as keys to move forward or backward

Reference: https://superuser.com/questions/436607/vlc-media-keys-and-stopping-and-starting-second-by-second

Thanks

**Comment by zhiyiYo** [comment]
The fast forward and fast rewind functions have been implemented in the latest commit, and the fast keys are the right and left arrows. But I don't think it's necessary to add a option to adjust jump size.

**Comment by javadevelopment4** [comment]
I have downloaded Groove_v1.2.3_x64_setup.exe but unable to see the icons..neither right and left arrows doesn't work....

Can you please attach a screenshots or steps?

**Comment by javadevelopment4** [comment]
![image](https://user-images.githubusercontent.com/61599369/209456770-dd966c8c-3000-4853-af62-ddf24c68a17d.png)

**Comment by zhiyiYo** [comment]
This feature is not included in v1.2.3, you need to download the source code and use pyinstaller to compile it, or you can replace Groove.exe in the installation directory with the Groove.exe I uploaded.
[Groove.zip](https://github.com/zhiyiYo/Groove/files/10299445/Groove.zip)
