### ISSUE TITLE
Highlight Tip to move to exact second quickly

### ISSUE THREAD

**Issue by javadevelopment4** [zhiyiYo/Groove#66]
Hi,

Is it possible to add a highlight tool tip when we move the cursor in the player with time like in other players.

![image](https://user-images.githubusercontent.com/61599369/209373192-847628e1-400c-4a79-8c42-f6db610dc656.png)

Thanks,

**Comment by zhiyiYo** [comment]
There are some problems with the slider adding tooltips, see https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/2
