### ISSUE TITLE
Song title junk characters vs file location name is NOT junk

### ISSUE THREAD

**Issue by javadevelopment4** [zhiyiYo/Groove#67]
![image](https://user-images.githubusercontent.com/61599369/209457072-598234a9-8218-4dad-963f-4a1ba18d88dd.png)

File Name:  கர்த்தரையும், அவர் வசனத்தையும்,

Song title displays junk characters 
File location displays it correctly

**Comment by zhiyiYo** [comment]
It has to do with the metadata of your song, and all I can do is read and display it in the dialog. You can use the Song Information Edit dialog to modify the title.
