### ISSUE TITLE
界面标签文字错位

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/Groove#68]
最近播放和播放列表部分标签文字错位

win11系统

![QQ截图20230123185308](https://user-images.githubusercontent.com/104692238/214022895-11f848ba-3bc5-497c-aa01-8454afef9302.png)
![QQ截图20230123185325](https://user-images.githubusercontent.com/104692238/214022929-3b6f4a2c-3f77-4827-b49d-acace26bba65.png)

**Comment by zhiyiYo** [comment]
我这边没有这个问题诶，你是跑的最新代码还是运行的 exe 呀
![image](https://user-images.githubusercontent.com/65096819/214023947-bfd2da13-1f1b-409a-beb8-97b66e098fb0.png)

**Comment by zhiyiYo** [comment]
可以试下代码吗🤔

**Comment by Ephemeralwanning** [comment]
> 可以试下代码吗🤔

我先尝试一下

**Comment by Ephemeralwanning** [comment]
这个环境安装不换源巨慢...
似乎还是错位
![QQ截图20230123200039](https://user-images.githubusercontent.com/104692238/214035094-4892ddcc-b61c-4655-9213-46a36e6ec997.png)
![QQ截图20230123200053](https://user-images.githubusercontent.com/104692238/214035112-dd013f34-4265-4788-b45f-d9235df3fc68.png)

**Comment by zhiyiYo** [comment]
有点奇怪，如果字体都是微软雅黑不应该发送错位的，要不试下加几个音乐文件夹进去康康？

**Comment by Ephemeralwanning** [comment]
> 有点奇怪，如果字体都是微软雅黑不应该发生错位的，要不试下加几个音乐文件夹进去康康？

试过了 依旧错位

**Comment by zhiyiYo** [comment]
只有这里错位了吗，感觉你的其他地方也会有这种问题，暂时不知道要怎么解决我无法复现的bug

**Comment by zhiyiYo** [comment]
@Ephemeralwanning 
刚才提交了一个 commit，你可以试下最新代码还有错位问题吗

**Comment by zhiyiYo** [comment]
在别人电脑上测试过已经解决文本错位问题了，你可以升级到 v1.3.1 来体验最新版的 Groove

**Comment by Ephemeralwanning** [comment]
> 在别人电脑上测试过已经解决文本错位问题了，你可以升级到 v1.3.1 来体验最新版的 Groove

已经正常了 辛苦
