### ISSUE TITLE
打开软件后提示`no OPENSSL_Applink`

### ISSUE THREAD

**Issue by youth54** [zhiyiYo/Groove#69]
**Describe the bug**
使用的版本：Groove_v1.3.1_windows_x64.zip
Windows11系统

作者您好，我下载打开软件后，有如下错误提示，这种是什么情况呢？
![image](https://user-images.githubusercontent.com/72968849/215326612-c4b568bf-cb81-4add-8e9a-b2f9fcf6cf77.png)

**Comment by zhiyiYo** [comment]
有试过 setup.exe 吗

**Comment by zhiyiYo** [comment]
如果 setup.exe 安装的软件还是有这个问题的话就只能克隆代码然后自己搭环境来跑了

**Comment by youth54** [comment]
> 如果 setup.exe 安装的软件还是有这个问题的话就只能克隆代码然后自己搭环境来跑了

刚才试了一些setup.exe，还是有这个问题。那我先搭建环境试试看

**Comment by zhiyiYo** [comment]
@youth54 
直接跑代码还有这个问题吗

**Comment by youth54** [comment]
> @youth54 
> 直接跑代码还有这个问题吗

搭建环境，用源代码跑没有问题，可以正常使用。

**Comment by zhiyiYo** [comment]
ok
