### ISSUE TITLE
How to specify hour in LRC file ?

### ISSUE THREAD

**Issue by passionate2023** [zhiyiYo/Groove#70]
Hi,

Can you please provide an example on how to specify LRC file format for hours?

Basically one audio is having more than 2 hours...

I couldn't achieve hours ..Pls advise

Thanks

**Comment by zhiyiYo** [comment]
You can convert hours to minutes

**Comment by passionate2023** [comment]
any sample or example text would be helpful?

**Comment by zhiyiYo** [comment]
The lyric format of `.lrc` file is **[mm:ss.xx]**，where **mm** is minutes, **ss** is seconds and **xx** is hundredths of a second.
```txt
[ti:Lyric Demo]
[ar:zhiyiYo]
[au:Written by zhiyiYo, 2022]
[al:Groove - Vol. 2 – Melody]

[00:12.00]zhiyiYo - Lyric Demo
[00:15.30]hello
[00:15.30]你好 # duplatcate time tag to add translation
[01:02.30]world
[01:04.29]shoko is so kawaii🥰
```

**Comment by zhiyiYo** [comment]
You can also view the [online help document](https://groove-music.readthedocs.io/zh/latest/user-guide/lyrics-format.html), but it is written in Chinese

**Comment by passionate2023** [comment]
> The lyric format of `.lrc` file is **[mm:ss.xx]**，where **mm** is minutes, **ss** is seconds and **xx** is hundredths of a second.
> 
> ```
> [ti:Lyric Demo]
> [ar:zhiyiYo]
> [au:Written by zhiyiYo, 2022]
> [al:Groove - Vol. 2 – Melody]
> 
> [00:12.00]zhiyiYo - Lyric Demo
> [00:15.30]hello
> [00:15.30]你好 # duplatcate time tag to add translation
> [01:02.30]world
> [01:04.29]shoko is so kawaii🥰
> ```

This doesn't have the hour...That's the issue

**Comment by zhiyiYo** [comment]
But this is the standard format. You should convert hours to minutes like this:
```txt
[72:04.29]abababa....  # 1h 12m 4.29s
```

**Comment by passionate2023** [comment]
[72:04.29]abababa....  # 1h 12m 4.29s

Can we also do like the below ? will it work....

01:12:04.29 

Many albums are more than 1 hours.....Example - https://www.youtube.com/watch?v=7UfM7Lkw4U4&ab_channel=ChillVibes

**Comment by zhiyiYo** [comment]
> Many albums are more than 1 hours.....Example - https://www.youtube.com/watch?v=7UfM7Lkw4U4&ab_channel=ChillVibes

This is a combination of multiple songs. The length of each song doesn't exceed one hour.
If you can provide lyrics in lrc format for more than one hour, I may consider adding this feature.
