### ISSUE TITLE
Windows 程序权限处理不当导致的问题

### ISSUE THREAD

**Issue by LemonFan-maker** [zhiyiYo/Groove#71]
**Describe the bug**

1. 双击运行桌面快捷方式提示*permission denied*每次使用必须获取管理员权限。

**To Reproduce**

双击桌面快捷方式提示permission denied

<img width="416" alt="报错信息" src="https://user-images.githubusercontent.com/115965270/217590514-a95118af-44d8-4ec0-bb71-dfe07f58edb0.png">

**Expected behavior**

**Environment(please complete the following information):**
 - OS: Microsoft Windows 11 专业工作站版(22H2) x64
 - DPI scaling: 125%

**Additional context**

看了日志文件，没有什么特别的(因为就是空的)。

**个人意见**

可以将Windows 的安装目录修改为`C:\Users\用户名名称\AppData\Local\Programs`避免权限不足造成的不必要报错。

**Comment by zhiyiYo** [comment]
感谢建议，之后会加个修改缓存目录选项的，目前你可以用管理员权限运行来避免权限不足的问题

**Comment by zhiyiYo** [comment]
v1.3.2 已解决该问题
