### ISSUE TITLE
Store log in to local file for better bug report

### ISSUE THREAD

**Issue by wxguy** [zhiyiYo/Groove#73]
This issue is related to the bug report I created earlier. If I understood correctly, the logging is currently done in the terminal (I assume so as there is no documentation that says about the local log file).  In my case, the terminal produces a lot of messages, in addition to the Groove log as indicated below:-

```
(Groove:3134): GLib-GObject-CRITICAL **: 21:13:02.422: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(Groove:3134): GStreamer-CRITICAL **: 21:13:02.422: gst_object_ref: assertion 'object != NULL' failed

(Groove:3134): GStreamer-CRITICAL **: 21:13:02.422: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(Groove:3134): GStreamer-CRITICAL **: 21:13:02.422: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed

(Groove:3134): GStreamer-CRITICAL **: 21:13:02.422: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(Groove:3134): GStreamer-CRITICAL **: 21:13:02.422: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(Groove:3134): GStreamer-CRITICAL **: 21:13:02.422: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

```

Since it becomes difficult to read the actual error message, I feel that you should store the log in-to a local file and request users to paste the log file content while filling the bug report.

**Comment by zhiyiYo** [comment]
The log message is stored in the data folder, which is `C:/Users/<UserName>/AppData/Roaming/Groove` on Windows, and `/home/<UserName>/.local/share/Groove` on Linux. Gstreamer's log messages are not under my control, so they will not be stored in log file.
