### ISSUE TITLE
Long speech mp3 files

### ISSUE THREAD

**Issue by passionate2023** [zhiyiYo/Groove#74]
Hi,

I have long speech mp3 files which have been converted youtube video to mp3 and also collection songs which plays for hours.

But none of them couldn't be defined with lyrics since it is more than 1 hr or 2 hrs (https://github.com/zhiyiYo/Groove/issues/70)

Could you please help me with a working example?

Thanks

**Comment by zhiyiYo** [comment]
dulplicate with #70
