### ISSUE TITLE
有的曲子开始播放时有一个click

### ISSUE THREAD

**Issue by ClanEver** [zhiyiYo/Groove#77]
**Describe the bug**
有的曲子开始播放时有一个click

**To Reproduce**
https://github.com/zhiyiYo/Groove/assets/73160783/db9524e4-d148-46ee-8e36-cf9ffdf39105

**Environment(please complete the following information):**
 - OS: Windows 10 19045.2486
 - Groove: 1.3.3
 - LAV Filters: 0.74.0

**Additional context**
所用曲子都是mp3

**Comment by ClanEver** [comment]
链接里是段录屏

**Comment by zhiyiYo** [comment]
没看懂视频里面有什么问题

**Comment by ClanEver** [comment]
click→爆音

**Comment by zhiyiYo** [comment]
这个应该是解码器的问题

**Comment by ClanEver** [comment]
![image](https://github.com/zhiyiYo/Groove/assets/73160783/0b55fb86-5f58-43d9-8e57-366cab8f0e6b)

**Comment by zhiyiYo** [comment]
换个更新的 LAVFilters 试试

**Comment by ClanEver** [comment]
好的 我试试
