### ISSUE TITLE
关于在线音乐以及歌词问题

### ISSUE THREAD

**Issue by SaharaMiyoko** [zhiyiYo/Groove#81]
~其实有可能是自己不会用~
~其实对我来说在线音乐其实是个无关紧要的功能，可以去lx或者ytb music下并且自己还有会员，只不过强迫症发作~
**Describe the bug**
在线音乐疑似无法使用，同时自动检索功能无法开启，并且从lx-music下载的lrc无法识别

**To Reproduce**

<img width="760" alt="屏幕截图 2023-07-11 222420" src="https://github.com/zhiyiYo/Groove/assets/104242390/bc51138e-1945-43ac-97fa-49448bb5005c">
<img width="758" alt="屏幕截图 2023-07-11 222439" src="https://github.com/zhiyiYo/Groove/assets/104242390/26048510-098d-4811-8224-ad6cdba959cd">
<img width="758" alt="屏幕截图 2023-07-11 223635" src="https://github.com/zhiyiYo/Groove/assets/104242390/abc1a89e-338a-45e9-b70a-4ec0217fb5e0">

Lrc(直接扔仓库了懒)https://github.com/SaharaMiyoko/temporary-repository/raw/main/585950.lrc

**Environment(please complete the following information):**
 - OS: Windows 11 22621.1848

**Additional context**
希望桌面歌词支持关闭卡拉OK样式

**Comment by zhiyiYo** [comment]
已修复此问题

**Comment by zhiyiYo** [comment]
发现 token 存在过期问题

**Comment by SaharaMiyoko** [comment]
🆗，我先试试

**Comment by SaharaMiyoko** [comment]
好像没有什么变化🤔，并且我把lx的歌词中罗马音与翻译调换了一下居然可以识别了🤣
<img width="747" alt="屏幕截图 2023-07-15 152951" src="https://github.com/zhiyiYo/Groove/assets/104242390/bf69bda9-d0ed-47cc-a2ab-d68dabf13ab2">

**Comment by zhiyiYo** [comment]
在线音乐接口还是有问题

**Comment by SaharaMiyoko** [comment]
是裤O音乐吗？

**Comment by zhiyiYo** [comment]
再次修复了此问题
