### ISSUE TITLE
win11 4K屏 显示异常

### ISSUE THREAD

**Issue by kangshifu2022** [zhiyiYo/Groove#84]
打开默认就全屏，显示“xxx无选择器xx”，无法关闭。只能通过任务管理器来关掉。

**Comment by zhiyiYo** [comment]
设置界面调一下缩放比。

**Comment by zhiyiYo** [comment]
无选择器是因为你没在设置界面选择音乐文件夹

**Comment by kangshifu2022** [comment]
软件一打开，就全屏并超出屏幕，找不到任何按钮，我提到的那些字在左上角也显示不全，并且无法关闭。只能任务管理器关闭。

我猜测是4k屏，250%缩放的原因。

**Comment by zhiyiYo** [comment]
可以先在windows设置里面把缩放比调低，然后启动软件，接着去设置界面调整缩放比
